// Sample Data for Vendor-wise Sales Report

export const vendors = [
  { id: "v1", name: "TechGear Solutions", location: "Mumbai, India" },
  { id: "v2", name: "Fashion Hub Co.", location: "Delhi, India" },
  { id: "v3", name: "Home Essentials Ltd.", location: "Bangalore, India" },
  { id: "v4", name: "Sports World Inc.", location: "Chennai, India" },
  { id: "v5", name: "Beauty & Glow", location: "Pune, India" },
];

export const categories = [
  { id: "cat1", name: "Electronics" },
  { id: "cat2", name: "Fashion" },
  { id: "cat3", name: "Home & Garden" },
  { id: "cat4", name: "Sports" },
  { id: "cat5", name: "Beauty" },
];

export const subCategories = [
  { id: "sub1", name: "Audio Devices", categoryId: "cat1" },
  { id: "sub2", name: "Wearables", categoryId: "cat1" },
  { id: "sub3", name: "Accessories", categoryId: "cat1" },
  { id: "sub4", name: "Women's Clothing", categoryId: "cat2" },
  { id: "sub5", name: "Men's Clothing", categoryId: "cat2" },
  { id: "sub6", name: "Footwear", categoryId: "cat4" },
  { id: "sub7", name: "Fitness Equipment", categoryId: "cat4" },
  { id: "sub8", name: "Skincare", categoryId: "cat5" },
  { id: "sub9", name: "Makeup", categoryId: "cat5" },
  { id: "sub10", name: "Kitchen", categoryId: "cat3" },
];

export const products = [
  {
    id: "p1",
    name: "Wireless Headphones",
    category: "Electronics",
    categoryId: "cat1",
    subCategory: "Audio Devices",
    subCategoryId: "sub1",
    vendor: "TechGear Solutions",
    vendorId: "v1",
    totalRevenue: 25650,
    totalUnits: 342,
    codRevenue: 15390,
    codUnits: 205,
    prepaidRevenue: 10260,
    prepaidUnits: 137,
    rating: 4.5,
  },
  {
    id: "p2",
    name: "Smart Watch Pro",
    category: "Electronics",
    categoryId: "cat1",
    subCategory: "Wearables",
    subCategoryId: "sub2",
    vendor: "TechGear Solutions",
    vendorId: "v1",
    totalRevenue: 28700,
    totalUnits: 287,
    codRevenue: 11480,
    codUnits: 115,
    prepaidRevenue: 17220,
    prepaidUnits: 172,
    rating: 4.7,
  },
  {
    id: "p3",
    name: "Laptop Stand",
    category: "Electronics",
    categoryId: "cat1",
    subCategory: "Accessories",
    subCategoryId: "sub3",
    vendor: "TechGear Solutions",
    vendorId: "v1",
    totalRevenue: 12690,
    totalUnits: 423,
    codRevenue: 8853,
    codUnits: 296,
    prepaidRevenue: 3837,
    prepaidUnits: 127,
    rating: 4.3,
  },
  {
    id: "p4",
    name: "USB-C Hub",
    category: "Electronics",
    categoryId: "cat1",
    subCategory: "Accessories",
    subCategoryId: "sub3",
    vendor: "TechGear Solutions",
    vendorId: "v1",
    totalRevenue: 16920,
    totalUnits: 564,
    codRevenue: 10152,
    codUnits: 338,
    prepaidRevenue: 6768,
    prepaidUnits: 226,
    rating: 4.2,
  },
  {
    id: "p5",
    name: "Bluetooth Speaker",
    category: "Electronics",
    categoryId: "cat1",
    subCategory: "Audio Devices",
    subCategoryId: "sub1",
    vendor: "TechGear Solutions",
    vendorId: "v1",
    totalRevenue: 14900,
    totalUnits: 298,
    codRevenue: 7450,
    codUnits: 149,
    prepaidRevenue: 7450,
    prepaidUnits: 149,
    rating: 4.6,
  },
  {
    id: "p6",
    name: "Summer Dress",
    category: "Fashion",
    categoryId: "cat2",
    subCategory: "Women's Clothing",
    subCategoryId: "sub4",
    vendor: "Fashion Hub Co.",
    vendorId: "v2",
    totalRevenue: 22800,
    totalUnits: 456,
    codRevenue: 18240,
    codUnits: 365,
    prepaidRevenue: 4560,
    prepaidUnits: 91,
    rating: 4.4,
  },
  {
    id: "p7",
    name: "Running Shoes",
    category: "Sports",
    categoryId: "cat4",
    subCategory: "Footwear",
    subCategoryId: "sub6",
    vendor: "Sports World Inc.",
    vendorId: "v4",
    totalRevenue: 38700,
    totalUnits: 387,
    codRevenue: 15480,
    codUnits: 155,
    prepaidRevenue: 23220,
    prepaidUnits: 232,
    rating: 4.5,
  },
  {
    id: "p8",
    name: "Face Cream",
    category: "Beauty",
    categoryId: "cat5",
    subCategory: "Skincare",
    subCategoryId: "sub8",
    vendor: "Beauty & Glow",
    vendorId: "v5",
    totalRevenue: 18690,
    totalUnits: 623,
    codRevenue: 7476,
    codUnits: 249,
    prepaidRevenue: 11214,
    prepaidUnits: 374,
    rating: 4.8,
  },
  {
    id: "p9",
    name: "Yoga Mat",
    category: "Sports",
    categoryId: "cat4",
    subCategory: "Fitness Equipment",
    subCategoryId: "sub7",
    vendor: "Sports World Inc.",
    vendorId: "v4",
    totalRevenue: 15400,
    totalUnits: 385,
    codRevenue: 9240,
    codUnits: 231,
    prepaidRevenue: 6160,
    prepaidUnits: 154,
    rating: 4.4,
  },
  {
    id: "p10",
    name: "Lipstick Set",
    category: "Beauty",
    categoryId: "cat5",
    subCategory: "Makeup",
    subCategoryId: "sub9",
    vendor: "Beauty & Glow",
    vendorId: "v5",
    totalRevenue: 23610,
    totalUnits: 787,
    codRevenue: 11805,
    codUnits: 394,
    prepaidRevenue: 11805,
    prepaidUnits: 393,
    rating: 4.6,
  },
];

export const vendorWiseData = [
  {
    id: "v1",
    name: "TechGear Solutions",
    location: "Mumbai, India",
    totalRevenue: 98860,
    totalOrders: 1914,
    totalProfit: 29658,
    avgOrderValue: 51.65,
    productsSold: 5,
    totalReturns: 47,
    avgRating: 4.46,
    topProduct: "Smart Watch Pro",
    growth: 15.2,
    codRevenue: 53325,
    codOrders: 1103,
    prepaidRevenue: 45535,
    prepaidOrders: 811,
  },
  {
    id: "v2",
    name: "Fashion Hub Co.",
    location: "Delhi, India",
    totalRevenue: 78200,
    totalOrders: 1564,
    totalProfit: 23460,
    avgOrderValue: 50.0,
    productsSold: 3,
    totalReturns: 68,
    avgRating: 4.3,
    topProduct: "Summer Dress",
    growth: 12.8,
    codRevenue: 54740,
    codOrders: 1095,
    prepaidRevenue: 23460,
    prepaidOrders: 469,
  },
  {
    id: "v3",
    name: "Home Essentials Ltd.",
    location: "Bangalore, India",
    totalRevenue: 56800,
    totalOrders: 1136,
    totalProfit: 17040,
    avgOrderValue: 50.0,
    productsSold: 2,
    totalReturns: 34,
    avgRating: 4.4,
    topProduct: "Kitchen Set",
    growth: 8.5,
    codRevenue: 36992,
    codOrders: 739,
    prepaidRevenue: 19808,
    prepaidOrders: 397,
  },
  {
    id: "v4",
    name: "Sports World Inc.",
    location: "Chennai, India",
    totalRevenue: 54100,
    totalOrders: 772,
    totalProfit: 16230,
    avgOrderValue: 70.08,
    productsSold: 2,
    totalReturns: 28,
    avgRating: 4.45,
    topProduct: "Running Shoes",
    growth: 18.3,
    codRevenue: 24720,
    codOrders: 386,
    prepaidRevenue: 29380,
    prepaidOrders: 386,
  },
  {
    id: "v5",
    name: "Beauty & Glow",
    location: "Pune, India",
    totalRevenue: 42300,
    totalOrders: 1410,
    totalProfit: 12690,
    avgOrderValue: 30.0,
    productsSold: 2,
    totalReturns: 22,
    avgRating: 4.7,
    topProduct: "Face Cream",
    growth: 22.1,
    codRevenue: 19281,
    codOrders: 643,
    prepaidRevenue: 23019,
    prepaidOrders: 767,
  },
];

export const categoryWiseData = [
  {
    id: "cat1",
    name: "Electronics",
    revenue: 98860,
    orders: 1914,
    productCount: 5,
    growth: 15.2,
    percentage: 38,
    codRevenue: 53325,
    prepaidRevenue: 45535,
  },
  {
    id: "cat2",
    name: "Fashion",
    revenue: 78200,
    orders: 1564,
    productCount: 1,
    growth: 12.8,
    percentage: 31,
    codRevenue: 54740,
    prepaidRevenue: 23460,
  },
  {
    id: "cat3",
    name: "Home & Garden",
    revenue: 56800,
    orders: 1136,
    productCount: 1,
    growth: 8.5,
    percentage: 22,
    codRevenue: 36992,
    prepaidRevenue: 19808,
  },
  {
    id: "cat4",
    name: "Sports",
    revenue: 54100,
    orders: 772,
    productCount: 2,
    growth: 18.3,
    percentage: 21,
    codRevenue: 24720,
    prepaidRevenue: 29380,
  },
  {
    id: "cat5",
    name: "Beauty",
    revenue: 42300,
    orders: 1410,
    productCount: 2,
    growth: 22.1,
    percentage: 17,
    codRevenue: 19281,
    prepaidRevenue: 23019,
  },
];

export const subCategoryWiseData = [
  {
    id: "sub1",
    name: "Audio Devices",
    categoryName: "Electronics",
    categoryId: "cat1",
    revenue: 40550,
    orders: 640,
    productCount: 2,
    growth: 16.5,
    codRevenue: 22840,
    prepaidRevenue: 17710,
  },
  {
    id: "sub2",
    name: "Wearables",
    categoryName: "Electronics",
    categoryId: "cat1",
    revenue: 28700,
    orders: 287,
    productCount: 1,
    growth: 18.2,
    codRevenue: 11480,
    prepaidRevenue: 17220,
  },
  {
    id: "sub3",
    name: "Accessories",
    categoryName: "Electronics",
    categoryId: "cat1",
    revenue: 29610,
    orders: 987,
    productCount: 2,
    growth: 12.3,
    codRevenue: 19005,
    prepaidRevenue: 10605,
  },
  {
    id: "sub4",
    name: "Women's Clothing",
    categoryName: "Fashion",
    categoryId: "cat2",
    revenue: 22800,
    orders: 456,
    productCount: 1,
    growth: 12.8,
    codRevenue: 18240,
    prepaidRevenue: 4560,
  },
  {
    id: "sub6",
    name: "Footwear",
    categoryName: "Sports",
    categoryId: "cat4",
    revenue: 38700,
    orders: 387,
    productCount: 1,
    growth: 20.1,
    codRevenue: 15480,
    prepaidRevenue: 23220,
  },
  {
    id: "sub7",
    name: "Fitness Equipment",
    categoryName: "Sports",
    categoryId: "cat4",
    revenue: 15400,
    orders: 385,
    productCount: 1,
    growth: 15.8,
    codRevenue: 9240,
    prepaidRevenue: 6160,
  },
  {
    id: "sub8",
    name: "Skincare",
    categoryName: "Beauty",
    categoryId: "cat5",
    revenue: 18690,
    orders: 623,
    productCount: 1,
    growth: 24.5,
    codRevenue: 7476,
    prepaidRevenue: 11214,
  },
  {
    id: "sub9",
    name: "Makeup",
    categoryName: "Beauty",
    categoryId: "cat5",
    revenue: 23610,
    orders: 787,
    productCount: 1,
    growth: 20.2,
    codRevenue: 11805,
    prepaidRevenue: 11805,
  },
];
